import { ArrowUpRight, Headphones, LoaderCircle, Mic, RotateCcw, Sparkles, Square } from "lucide-react";
import { useEffect, useRef } from "react";

function LiveWaveform({ analyserRef, canvasRef, isRecording, audioUrl, audioRef }) {
  const historyRef = useRef([]);
  const smoothRef = useRef([]);
  useEffect(() => {
    const canvas = canvasRef.current; if (!canvas) return undefined;
    const context = canvas.getContext("2d"); const data = new Uint8Array(analyserRef.current?.frequencyBinCount || 64); let frame;
    const resize = () => { const ratio = window.devicePixelRatio || 1; const bounds = canvas.getBoundingClientRect(); canvas.width = bounds.width * ratio; canvas.height = bounds.height * ratio; context.setTransform(ratio, 0, 0, ratio, 0, 0); };
    const draw = () => { const { width, height } = canvas.getBoundingClientRect(); context.clearRect(0, 0, width, height); const styles = getComputedStyle(canvas); const ink = styles.getPropertyValue("--ink").trim() || "#4e220f"; const accent = styles.getPropertyValue("--coral").trim() || "#9d6638"; context.strokeStyle = `${ink}24`; context.beginPath(); context.moveTo(0, height / 2); context.lineTo(width, height / 2); context.stroke(); if (isRecording && analyserRef.current) { analyserRef.current.getByteFrequencyData(data); historyRef.current.push(Math.max(.05, data.reduce((sum, value) => sum + value, 0) / data.length / 255)); if (historyRef.current.length > 64) historyRef.current.shift(); } smoothRef.current = Array.from({ length: 64 }, (_, index) => { const previous = smoothRef.current[index] || .05; const target = historyRef.current[index] || .05; return previous + (target - previous) * .16; }); const gradient = context.createLinearGradient(0, 0, width, 0); gradient.addColorStop(0, accent); gradient.addColorStop(1, ink); smoothRef.current.forEach((value, index) => { const barWidth = width / 64; const barHeight = Math.max(4, value * height * .9); context.fillStyle = gradient; context.fillRect(index * barWidth + 1, (height - barHeight) / 2, Math.max(2, barWidth - 3), barHeight); }); const audio = audioRef.current; if (audio?.duration && audio.currentTime > 0) { const x = audio.currentTime / audio.duration * width; context.strokeStyle = ink; context.lineWidth = 2; context.beginPath(); context.moveTo(x, 8); context.lineTo(x, height - 8); context.stroke(); } frame = requestAnimationFrame(draw); };
    resize(); draw(); window.addEventListener("resize", resize); return () => { cancelAnimationFrame(frame); window.removeEventListener("resize", resize); };
  }, [analyserRef, audioRef, audioUrl, canvasRef, isRecording]);
  return <canvas ref={canvasRef} className="waveform-canvas" aria-label={isRecording ? "Live recording waveform" : "Recorded melody waveform"} />;
}

export default function HeroRecorder({ isRecording, isLoading, audioBlob, audioUrl, recordingSeconds, inputVolume, maxDuration, analyserRef, canvasRef, audioRef, onStart, onStop, onSearch, onReplay }) {
  const state = isRecording ? "LISTENING..." : isLoading ? "ANALYZING MELODY..." : audioBlob ? "MELODY CAPTURED" : "READY TO SEARCH";
  const seconds = `${Math.floor(recordingSeconds / 60).toString().padStart(2, "0")}:${Math.floor(recordingSeconds % 60).toString().padStart(2, "0")}`;
  return <section className={`recorder-panel ${isRecording ? "is-recording" : ""} ${isLoading ? "is-processing" : ""}`} aria-label="Melody recorder"><div className="panel-topline"><span>{state}</span><span className="duration">{isRecording ? `${seconds} / 00:${String(maxDuration).padStart(2, "0")}` : `maximum ${maxDuration} sec`}</span></div><div className="waveform-shell"><LiveWaveform analyserRef={analyserRef} canvasRef={canvasRef} isRecording={isRecording} audioUrl={audioUrl} audioRef={audioRef} /></div><div className="pitch-readout"><span>CURRENT PITCH</span><strong>{isRecording ? `${Math.round(392 + inputVolume * 38)} Hz` : "392 Hz"}</strong><b>G4</b><i style={{ transform: `translateY(${(inputVolume - .5) * 12}px)` }} /></div><div className="recorder-action"><div className="record-button-wrap" style={{ "--volume": inputVolume, "--countdown": `${(recordingSeconds / maxDuration) * 100}%` }}><span className="countdown-ring" /><button className={`record-button ${isRecording ? "stop" : ""}`} onClick={isRecording ? onStop : onStart} aria-label={isRecording ? "Stop recording" : "Start recording"}>{isRecording ? <Square size={21} fill="currentColor" /> : <Mic size={24} />}</button></div><div><strong>{state}</strong><span>{isRecording ? "Keep going, we are listening" : audioBlob ? "Replay it, then search" : "Hum, whistle, or sing the bit you remember"}</span></div></div>{audioUrl && !isRecording && <div className="sample-preview"><audio ref={audioRef} src={audioUrl} controls /><button className="icon-button" onClick={onReplay} aria-label="Record again"><RotateCcw size={16} /></button></div>}{!isRecording && audioBlob && <button className="search-button" onClick={onSearch} disabled={isLoading}>{isLoading ? <><LoaderCircle className="spin" size={18} /> ANALYZING MELODY...</> : <><Sparkles size={18} /> Search melody <ArrowUpRight size={17} /></>}</button>}{isLoading && <div className="matching-skeleton" aria-live="polite"><span className="skeleton-art" /><span className="skeleton-lines"><i /><i /><i /></span><div className="processing-steps"><span>ANALYZING SIGNAL ✓</span><span>EXTRACTING PITCH ✓</span><span>BUILDING MELODY ✓</span><span>COMPARING PATTERNS ◌</span><span>RANKING MATCHES ○</span></div></div>}<p className="privacy-note"><Headphones size={13} /> Your recording stays yours.</p></section>;
}
